services:
  db:
    image: postgres:17-alpine
    container_name: saga-transactions-db
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - '${DATABASE_PORT}:5432'
    volumes:
      - saga-transactions-db:/var/lib/postgresql/data

volumes:
  saga-transactions-db:
