spring:
  application:
    name: vacation
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
  liquibase:
    change-log: db/changelog/changelog.xml
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP}
    producer:
      acks: all
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        linger.ms: 100
        enable.idempotence: true
    consumer:
      group-id: jdmik11-${spring.application.name}-consumer-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      isolation-level: read_committed
      properties:
        spring.json.trusted.packages: "io.dd.test.core.kafka.*"
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer

server:
  port: 9001

app:
  kafka:
    backoff:
      interval: 500
      attempts: 5
    topics:
      vacation-command:
        name: "dd.vacation.command"
        partitions: 3
        replicas: 3
        min-in-sync-replicas: 2