spring:
  application:
    name: saga
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP}
    streams:
      properties:
        processing.guarantee: exactly_once_v2
        isolation.level: read_committed
        spring.json.trusted.packages: "io.dd.test.core.*"

server:
  port: 9005

logging:
  level:
    root: WARN
    io.dd.test: INFO

app:
  kafka:
    topics:
      saga-event:
        name: "dd.saga.event"
        partitions: 3
        replicas: 3
        min-in-sync-replicas: 2
      saga-state:
        name: "dd.saga.state.event"
      vacation-command:
        name: "dd.vacation.command"
      profiler-command:
        name: "dd.profiler.command"
      accounting-command:
        name: "dd.accounting.command"
      resources-command:
        name: "dd.resources.command"